---
  - name: Check operating system
    debug:
      msg: "The operating system is {{ ansible_facts['os_family'] }}"
    when: ansible_facts['os_family'] == "Debian"
  
  - name: Install Nginx on Server
    apt: 
      name: nginx 
      state: latest
  
  - name: Copy Nginx Index HTML 
    template:
      src: index.html.j2
      dest: /var/www/html/index.html 
  
  - name: Start and enable a service
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install required packages
    apt:
      name:
        - wget
        - gnupg

  - name: Add HashiCorp GPG key and repository
    shell: |
      wget -qO - https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

  - name: Update apt cache and install Consul
    apt:
      update_cache: yes
      name: consul
      state: present

  - name: Render Consul Configuration Template
    template:
      src: config.hcl.j2
      dest: /etc/consul.d/config.hcl
    vars:
      server: "false"
      datacenter: "dc1"
  
  - name: Render Consul Backend Template
    template:
      src: backend.hcl.j2
      dest: /etc/consul.d/backend.hcl

  - name: Create Consul systemd service unit
    template:
      src: consul.service.j2
      dest: /etc/systemd/system/consul.service
    
  - name: Reload systemd
    systemd:
      daemon_reload: yes

  - name: Start and enable Consul service
    systemd:
      name: consul
      state: started
      enabled: yes