---
  - name: Check operating system
    debug:
      msg: "The operating system is {{ ansible_facts['os_family'] }}"
    when: ansible_facts['os_family'] == "Debian"
  
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
  
  - name: Install Nginx on Server
    apt: 
      name: nginx 
      state: latest
  
  - name: Copy Nginx Index HTML 
    template:
      src: index.html.j2
      dest: /var/www/html/index.html 
  
  - name: Start and enable a service
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
  
  - name: Install Consul Server
    apt: 
      name: consul 
      state: latest

  - name: Render Consul Configuration Template
    template:
      src: config.hcl.j2
      dest: /etc/consul.d/config.hcl
    vars:
      server: "false"
      datacenter: "dc1"
  
  - name: Render Consul Backend Template
    template:
      src: backend.hcl.j2
      dest: /etc/consul.d/backend.hcl
  
  - name: Start Consul Agent Template
    shell: sudo consul agent -config-dir /etc/consul.d/ &
    register: consul_start
    ignore_errors: true